# Introduction

## Scientific Overview {-}

The AED modelling library (termed ‘**AED**’ for short) consists of numerous modules that are designed as individual model ‘components’ able to be configured in a way that facilitates custom aquatic ecosystem conceptualisations – from very simple to very complex. Think of it like a set of jigsaw pieces that connect together to build a complete picture. Users select water quality and ecosystem variables they wish to simulate and then are able to customize connections and dependencies with other modules, including support for easy customisation at an algorithm level how model components operate (e.g. photosynthesis functions, sorption algorithms etc).

In general, model components consider the cycling of carbon, nitrogen and phosphorus, and other relevant components such as oxygen, and are able to simulate organisms including different functional groups of phytoplankton and zooplankton, and also organic matter. Modules to support simulation of water column and sediment geochemistry, including coupled kinetic-equilibria, are also included.


## Application Contexts {-}

The modules have been applied across wetlands, lakes, rivers and estuaries, by taking advantage of the standard coupling interface between the scientific modules and hydrodynamic drivers. Due to this flexibility the model can be applied across a range of scales and contexts. For example through a 0D box model, the 1D model GLM, or the 3D finite volume model TUFLOW-FV.

Applications of the model include:

-	Hypoxia in lakes or estuaries
-	Fish-kill risks
-	Harmful algal blooms
-	Pathogen risk
-	Nutrient cycling
-	Greenhouse-gases
-	Habitat quality
-	Floodplain response
-	Invasive species
-	Food web studies


## Navigating this book {-}

This is not the sought of book you read from cover to cover! The book has initial introductory material in the first 4 chapters, and then is followed by 5 major sections:

1) Part I: AED Water - Descriptions of the core “water” modules, those relevant to simulating basic water quality in the pelagic environment.
2) Part II: AED+ Water -  Description of the advanced “plus” water modules.
3) Part III: AED+ Benthic -  Description of the advanced benthic modules.
4) Part IV: AED+ Riparian -  Description of the advanced riparian modules.
5) Part V: Supporting Material.

The chapters within the Parts I-IV of the book typically map to a specific module within the AED code library. Each describes the scientific context of the module, provides technical descriptions for the model processes, and the provides summary information on the required module parameters, and configuration details. Where available, the modules also include case-studies to demonstrate the functionality and publications using the module that can be referred to for further information.
