# Preface {-}

## Who is this book for? {-}

This book describes the scientific basis and technical details of the module within the AED library.

If you’re a new user seeking to get started with water quality modelling you may have undertaken a tutorial and interested to setup your own site for the first time. Or you may have your own conceptual model and keen to build a tailored setup to simulate your site. Or you may be ready to modify a module or create a whole new module for your research or management application.

Depending at what stage you are at in your model development journey, different parts of the book may be more relevant to you.

## Why AED? {-}

The AED modelling code-base is a community-driven library of modules and algorithms for simulation of "aquatic ecodynamics" - water quality, aquatic biogeochemistry, biotic habitat and aquatic ecosystem dynamics.

The AED software is unique as it is suitable for a very wide range water bodies types, including lakes, reservoirs, wetlands, ponds, estuaries and coastal waters. It has been applied to many research and water engineering projects across the world. Users select water quality and ecosystem variables they wish to simulate and are able to customize links and dependencies between modules.

Each <ins>module</ins> aims to be based on state-of-the-art science sourced from a wide variety of scientific literature, making the library one of the most advanced available to aquatic ecosystem modellers.

Importantly, this software is an open-source project, and the <ins>source code</ins> is accessible and customisable for specific applications. Most modules have numerous options and alternate algorithms so users can tailor the model to their specific needs, but inevitably, users will require flexibility to embed custom algorithms or functionality.

It is envisaged that the flexible nature of the model components will facilitate the model community to experiment with model structural complexity, to more easily share model innovations at the algorithm level, and support the development of common performance assessment approaches (for a discussion on model assessment, readers are referred to Hipsey et al., 2020).

## Acknowledgements {-}
