
# Pesticides {#Pesticide_1}

## Contributors

Thanh Hoang, Matthew R. Hipsey, Daniel Botelho, Jordan Glen

## Overview

The toxicity of pesticides is of particular concern in aquatic environments such as estuaries and lakes. It is estimated that during pest control operations, only a small amount of pesticides (often less than 1%) of the total applied pesticide reaches the target pest, while the remaining pesticide enters the soil and watercourses. Within aquatic systems, pesticides can separate between the dissolved and particulate phase depending on their water solubility, sorption to soil and the type of sediments. As pesticides have potential impacts and negative effects on aquatic species and ecosystem health, modelling their fate and transport is crucial for environmental risk assessments. The module, `aed_pesticides` ($\mathrm{PES}$), is designed for investigations of pesticide pollution, and is able to be linked to by other modules that interact with pesticides in the AED library.

## Model Description

This module supports several state variables to capture pesticide concentrations in aquatic environments. Most applied pesticides move into the aquatic environment and change through several complex physical and biogeochemical processes, including:

 - Advective-dispersive transport
 - Volatilisation
 - Photolysis
 - Hydrolysis
 - Sorption and desorption
 - Sedimentation and resuspension
 - Sorption and desorption
 - Biodegradation 

As pesticides in aquatic systems distribute among dissolved (aqueous) and particulate phases (sorbed onto particulate matter), these two forms are subject to different above mentioned processes that may degrade or increase their concentration. 

For the main dissolved pool in the sediments, denoted $C_d$, the relevant equation is:

\begin{eqnarray}
\frac{D}{Dt}C_d =  \color{darkgray}{ \mathbb{M} + \mathcal{S} } + \check{f}_{atm}^{pst}+\hat{f}_{dsf}^{pst} - {f}_{sorp}^{pst} \quad
&+& \overbrace{{f}_{photo-d}^{pst} - {f}_{hydrl-d}^{pst} - f_{uptake}^{pst}}^\text{breakdown}
\end{eqnarray}

where $\mathbb{M}$ and $\mathcal{S}$ refer to water mixing and boundary source terms, respectively, that are simulated by a host hydrodynamic and transport model, and the specific processes are volatilisation to the atmosphere ($\check{f}_{atm}^{pst}$), diffusive sediment fluxes of dissolved pesticides ($\hat{f}_{dsf}^{pst}$), orption (+ve) and desorption (-ve) of dissolved pesticide onto sorbents (DOC, POC, SS) (${f}_{sorp}^{pst}$), and breakdown processes by photolysis, hydrolysis, and biological uptake (${f}_{photo-d}^{pst}$, ${f}_{hydrl-d}^{pst}$, $f_{uptake}^{pst}$), respectively. 

The pesticides can sorb onto multiple particulate species as well as dissolved organic matter (often organic matter in a humic size category), which vary in their distributions throughout estuaries. For the fraction sorbed onto DOC, we apply the equation describing the processes is:

\begin{eqnarray}
\frac{D}{Dt}C_{doc} =  \color{darkgray}{ \mathbb{M} + \mathcal{S} } + \check{f}_{atm}^{pst}+\hat{f}_{dsf}^{pst} + {f}_{sorp-doc}^{pst} \quad
&-& \overbrace{{f}_{photo-doc}^{pst} - {f}_{hydrl-doc}^{pst}}^\text{breakdown}
\end{eqnarray}

The various particulate pools simulated include inorganic cohesive sediments (SS), particulate organic carbon (POC) and potentially also phytoplankton (PHY), denoted, $C_{ss}$, $C_{poc}$, and $C_{phy}$, respectively. The equation for the generic particulate group, $C_p$, is:

\begin{eqnarray}
\frac{D}{Dt}C_p =  \color{darkgray}{ \mathbb{M} + \mathcal{S} } + {f}_{sorp-p}^{pst} - {f}_{set-p}^{pst} \quad
&-& \overbrace{{f}_{photo-p}^{pst} - {f}_{hydrl-p}^{pst}}^\text{breakdown} + \hat{f}_{res-p}^{pst}
\end{eqnarray}

where ${f}_{set-p}^{pst}$ and $\hat{f}_{res-p}^{pst}$ represent sedimentation and resuspension of pesticide sorbed to the $P^{th}$ particulate group. 

The total pesticide concentration ($C_T$) in any computation cell is considered to the sum of the relevant pools, as follows:

\begin{eqnarray}
{C}_T = {C}_d + {C}_{doc} + \sum_{p} {C}_P
\end{eqnarray}


### Process Descriptions 

In the following sections, the specific equations for the relevant processes are described and parameterisations are outlined.

#### Volatilisation {-}

Volatilisation is an important process for the dissolved phase of pesticides in the surface water layer. In this module Volatilisation is modelled using the double film theory, in which a pesticide molecule diffuses across both the water layer and air layer, resolved as the flux, $F_{volat}$. The assumption is that the atmospheric concentration is effectively zero and the flux is proportional to the concentration gradient between air and water, and the gas transfer velocity.

The volumetric concentration change in the surface layer is captured as:

\begin{eqnarray}
\check{f}_{atm}^{pst} = -\frac{\mathcal{F}_{volat}}{\Delta z_{surf}} = -\frac{k_{600}^{pst}} {\Delta z_{surf}}{C_{d}}
\end{eqnarray}

where $\check{f}_{atm}^{pst}$, $\mathcal{F}_{volat}$, $k_{600}^{pst}$, $C_d$, and $\Delta z_{surf}$ represent the volatilisation rate, volatilisation mass flux and transfer coefficient, concentration of dissolved phase of a pesticide, and the surface layer thickness.

The $k_{600}^{pst}$ value is a function of wind speed, using commonly applied expressions for gas transfer rates (e.g. Wanninkhoff 1992). An alternative to estimate $k_{600}^{pst}$ value is to relate $k_{600}^{pst}$ to discharge (Q) as in many systems water velocity becomes the best available predictor of within-stream variation in $k_{600}^{pst}$ (Appling et al., 2018). By determining the relationships (e.g. linear, log-linear, or nonlinear) between $k_{600}^{pst}$ and water velocity the transfer coefficient can be estimated.

#### Diffusive Sediment Flux  {-}

Concentration gradients between porewaters and overlying water layer drive diffusive fluxes of dissolved contaminants across the sediment-water interface. Benthic fluxes of dissolved contaminants release contaminants from the sediment layer and play an important role as internal sources of contaminants, contributing to increased pollutant concentrations in the aquatic environment. Generally, when the flow velocity is low, the diffusive flux is considerably greater than the convective flux (Zhao et al., 2017), with the diffusive flux being highly influenced by temperature, sediment tortuosity, and salinity (Percuoco et al., 2015). A convective flux of chemicals accumulated in the sediment to the overlying water generally becomes important where strong vertical density gradients occur between water and sediment, and mediated by the nature of the interstitial space (e.g., porosity) within the sediments.

Diffusive flux of pesticides from the sediment can be estimated according to Fick’s first law of diffusion (Boudreau, 1996), as follow:

\begin{eqnarray}
f_{dif}^{pst} =-\varphi\frac{D_{s}}{\theta^2} \frac{\partial c}{\partial z} \tag{...}
\end{eqnarray}

where:

* $f_{dif}^{pst}$ is the diffusive flux of pesticides from the sediment with concentration c at depth z 
* $D_s$ is the effective diffusion coefficient of sediment corrected for temperature

* $\varphi$ is the porosity of the sediment

* $\Theta$ is the diffusive tortuosity of the sediment

* $\frac{\partial c}{\partial z}$ is the concentration gradient estimated from the slope of the straight line at the water-sediment interface (z = 0)

Because direct measurement of $D_s$ may be difficult, it is often empirically estimated through the correlation between the diffusion coefficient of an infinitely diluted solution ($D_0$) and porosity ($\varphi$) (Ullman & Sandstrom, 1987):

\begin{align}
  D_s &= \varphi D_0 &&\text{(when $\varphi$ ≤ 0.7)}\\
  D_s &= \varphi^2 D_0 &&\text{(when $\varphi$ > 0.7)}\\
\end{align}


#### Breakdown processes {-}

##### Photolysis {-}

In aquatic systems pesticides in dissolved or sorbed phases absorb light and decompose spontaneously or by reaction with secondary reagents, termed photolysis. The rate of photolysis depends on light intensity and the response of the irradiated pesticides. The light intensity decreases exponentially with depth of water such that $I=I[z]$. The exponential light attenuation is calculated as $I=I_o e^{-kz}$, where $I_o$ is the irradiance at the surface $(W/m^2)$, k is a light attenuation coefficient (1/day) and z is the water depth. In natural water systems the rate of attenuation of irradiance depends upon absorption by water itself and constituent elements of the water body (e.g., phytoplankton, coloured dissolved organic matter, suspended sediments), and the optical path in the water body, which is determined by the angle of incidence of the light sources and scatting of light within the water body. Typically, the ultra-violet bandwidth is most effective in breaking down a pesticide molecule, though the ultraviolet light intensity is attenuated more quickly than visible wavelengths. Accurate resolution of photolysis in deeper and/or ‘optically complex’ water columns therefore necessitate bandwidth specific extinction coefficients to allow ultra-violet light profiles to differentiate from visible light.

The overall rate of photolysis of a pesticide, $f_{photo}^{pst}$, can be described as the sum of the component reactions:

\begin{eqnarray}
f_{photo}^{pst} = f_{photo-d}^{pst} + f_{photo-doc}^{pst} + \sum_{p} f_{photo-p}^{pst}
\end{eqnarray}

where the specific rate for each pool is defined as:

\begin{equation}
f_{photo-X}^{pst} = R_{photo} [I]  \gamma_X  C_X 
\end{equation}

where Photo-d, doc and p refer to dissolved, DOC and particulate-associated pesticides, and:

* $R_{photo}$ is the relative rate of photolysis of a pesticide, calculated as a function of light intensity, I.

* $\gamma_X$ is a photolysis efficiency fraction for the pesticide pool, X.

* $C_X$ is the concentration of a pesticide pool, X, in the water layer.

The parameters are therefore further detailed for each phase of pesticides to be photo-decomposed (i.e., dissolved, sorbed on DOC, POC and SS), and a photolysis efficiency fraction accounts for shading effects or other factors differentiating photolysis rates for each group. 

##### Hydrolysis {-}

Pesticides potentially react with a water molecule when there are catalysts such as protons, hydroxides, or sometimes inorganic ions (e.g., phosphate) present. Pesticide hydrolysis is a pH and temperature dependent process. Similar to photolysis process, the total rate of breakdown due to hydrolysis is the sum of the amount from each pool:

\begin{eqnarray}
f_{hydrl}^{pst} = f_{hydrl-d}^{pst} + f_{hydrl-doc}^{pst} + \sum_{p} f_{hydrl-p}^{pst}
\end{eqnarray}

The hydrolysis rate of each pesticide pool can be expressed:

\begin{eqnarray}
f_{hydrl-X}^{pst} = R_{hydrl} [T, pH] C_{X}
\end{eqnarray}

where:

* $f_{hydrl-X}^{pst}$ is the overall rate of hydrolysis of a pesticide pool

* $R_{hydrl}$ is the hydrolysis constant (kinetic constant) computed as a function of temperature (T) and pH 

* $C_X$ is the concentration of a pesticide pool, $X$, in the water layer where the pool has components of dissolved, DOC-sorbed and particulate pesticides.

##### Biodegradation and uptake  {-}

Various aquatic primary producers in aquatic systems can uptake pesticides as sources of carbon (DeLorenzo et al., 2001) as part of the process of biodegradation. Biodegradation is a generic term to indicate several processes relevant to pesticide breakdown (pesticides are decomposed to other products), bioaccumulation (pesticides are taken up and progressively concentrated by other organisms, biomagnification (pesticides are taken up and transmitted to other organisms through the food chain), and biotransformation (pesticides are transformed to other compoundsby organisms). Ignorging secondary metabolites, the rate of biodegradation of pesticides can be described as:

\begin{eqnarray}
f_{uptake}^{pst} = R_{biodeg} C_{d}
\end{eqnarray}

where $f_{uptake}^{pst}$ is the overall rate of biodegradation of a pesticide, $R_{biodeg}$ is biodegradation constant (first order kinetic constant), and $C_{d}$ is concentration of the dissolved pesticide in a given volume of water.

Since the rate of biodegradation varies in the dissolved phase and depending on the particulate material that the pesticide is sorbed on, it is necessary to estimate the biodegradable fraction of sorbents in aquatic systems. Servais et al. (1995) found that the average degradation rate of DOC was about 0.08 d-1 for the first week of incubation, and its concentration reached a stable level between 20 and 30 days of incubation. They also reported that the biodegradable rate of POC was considerably slower than DOC. The average decrease rate of POC was around 0.01 d-1 between 7 and 30 days of incubation, and the concentration reached a stable value between 30 and 45 days of incubation.

#### Adsorption and desorption  {-}

Sorption and desorption are fundamental processes that have major impacts on the fate of pesticides in aquatic environments (Holvoet et al., 2007). These processes occur both in the water column and the sediment and depend on both the nature of the particulate matter in the system (e.g., particle size distribution, type of clay mineral, clay content, organic matter content, cation exchange capacity) and the chemical characteristics of pesticides (e.g., polarity, water solubility, octanol-water partition coefficient, fugacity). In general, the ability of a pesticide sorbed onto sediment negatively correlates with its polarity (Petit et al., 1995). For pesticides with low polarity and low solubility, organic matter is considered the most important sorbent; however for more polarised solutes other materials in soils and sediments can become important sorbents (Wauchope et al., 2002). The presence of dissolved organic carbon (DOC) and particulate organic carbon (POC) considerably affects pesticide sorption and desorption behaviour as pesticides can bind to these materials, causing a change pesticide partitioning among these constituents in water, with different rates of pesticide loss (e.g., due to sedimentation of particulates) (Gao et al., 1998).

The sorption rate of a pesticide can be evaluated through two coefficients: the sorption partition coefficient ($k_d$ measured in L/kg) used for low concentrations of pesticides, and the adsorption coefficient ($k_{oc}$) used for the organic content of the sediment. For hydrophobic organic substances/pesticides, natural organic carbon is likely the dominant sorbent when its content in sediments exceeds 0.1%, therefore sorption can be estimated using $k_{oc}$ (Holvoet et al., 2007). For sediments with low organic carbon content, the sorption of pesticides is proportional to the cation exchange capacity, sediment surface and pH. Pesticides with high cationic exchange properties such as Diquat and Paraquat are commonly reported to be strongly sorbed on suspended materials and sediment and their sorption rates increase when pH decreases (Petit et al., 1995).

Sorbed pesticides can be desorbed and released back to the water. The desorption process from sediment (maybe similar to other sorbents) is commonly reported to be biphasic with a fast initial release, then a prolonged slower release of sorbed pesticides (Holvoet et al., 2007). The kinetic equation of sorption-desorption of a pesticide can be written as follows (Site, 2001):

\begin{eqnarray}
\frac{dC}{dt} = -k_1\:m\:C_d\:(q_c - q) + k_2\:q_m 
\end{eqnarray}

where:

* $q_c$ is sorption capacity of the system, defined as the ratio of the mass of sorbate (contaminant, pesticide) to the unit mass of sorbent (DOC, POC, SS)
* $m$ is the mass of the mass of the sorbent
* $q_cm$ represents the total sorption capacity
* $C_d$ is the dissolved concentration of the sorbate
* $q$ is fraction of the sorbate sorbed on the sorbent
* $k_1$ and $k_2$ are the sorption and desorption rates, respectively, and unique for each sorbate.

The rate of the sorption is assumed to be proportional to $C_d$ and to the difference between the total sorption capacity ($q_{cm}$) and the amount sorbed ($q_m$). It is worth noting that in some models the kinetics are not explicitly modelled and the partitioning is considered to be an equilibrium process, i.e., it is assumed to reach the equilibrium sorption ratio in each time step.

As the dissolved phase of a given pesticide can be sorbed on and desorbed from suspended sediment (SS), DOC and POC it is important to determine the fractions of a pesticide partitioned in each type of sorbent. In addition, sorption and desorption affinities need to be considered for each type of sorbent.

The rate of sorption can be expressed generally as follows:

\begin{eqnarray}
f_{sorp-j}^{pst} = R_{sorp-j} (C_{je}-C_J)
\end{eqnarray}

where:

* $f_{sorp-j}^{pst}$ is the overall rate of sorption or desorption of a pesticide compound on sorbent $j$
* $R_{sorp-j}$ is the sorption and desorption constant of pesticide for sorbent $j$ (kinetic constant)
* $C_{je}$  is  the equilibrium concentration of pesticide sorbed on sorbent $j$
* $C_j$ is the actual concentration of pesticide sorbed on sorbent $j$

The fractions of a pesticide partitioned between the sorbents can be estimated using the approach outlined for DelWAQ, which assume SS, DOC, POC and algae (PHY) are the dominant sorbents in aquatic systems (Deltares, 2019):

\begin{eqnarray}
C_T = (\chi_d + \chi_{ss} + \chi_{doc} + \chi_{poc} + \chi_{phy}C_T 
\end{eqnarray}

with  $\chi$ denotes the pesticide fraction of the total within a given pool. These fractions are computed by balancing the sorbent specific partitioning coefficients, according to:

\begin{eqnarray}
C_p = k_{p-ss}^{pst} C_{ss} + k_{p-poc}^{pst}(C_{poc} +  \gamma_{doc} C_{poc})
\end{eqnarray}

\begin{eqnarray}
\chi_d = \frac{\varphi} {\varphi + C_p}
\end{eqnarray}

\begin{eqnarray}
\chi_{ss} = (1-\chi_d) \frac{k_{p-ss}^{pst} C_{ss}} {C_p}
\end{eqnarray}

\begin{eqnarray}
\chi_{poc} = (1-\chi_d) \frac{k_{p-poc}^{pst} C_{poc}} {C_p}
\end{eqnarray}

\begin{eqnarray}
\chi_{doc} = (1-\chi_d) \frac{k_{p-poc}^{pst} \gamma_{doc} C_{poc}} {C_p} \tag{equation number}
\end{eqnarray}

where:

* $C_P$ is the total sorbed pesticide in water
* $\chi_d, \chi_{doc}, \chi_{ss},\chi_{poc}, \chi_{phy}$ are the fractions of a pesticide in dissolved phase, associated with dissolved organic carbon and sorbed on suspended sediment, particulate organic carbon and phytoplankton

* $C_{ss}, C_{poc}, C_{doc}$ are the concentration of suspended sediment, particulate organic carbon, and dissolved organic carbon, respectively

* $k_{p-ss}, k_{p-poc}$ are the partition coefficient for suspended sediment (m3 mg DW-1), particulate organic carbon

* $\gamma_{doc}$ are the attenuation factors for fraction associated with dissolved organic carbon

* $\varphi$: porosity


The partition coefficient is defined as a function of concentration of dissolved and particulate phases of pesticides and the concentration of particulate matter in water, as follows:

\begin{eqnarray}
k_{p-j}^{pst} = \frac{\varphi C_j} {JC_d} \tag{equation number}
\end{eqnarray}

where:

* $k_{p-j}^{pst}$ is the equilibrium partition coefficient for the $j^{th}$ sorbent in water
* $C_j$ is the particulate concentration of a pesticide in the $j^{th}$ group
* $J$ is the concentration of particulate matter
* $C_d$ is the dissolved concentration of a pesticide

The partition coefficient and kinetic sorbent rates can be defined for individual compounds, usually based on laboratory tests. 

#### Sedimentation  {-}

Sorbed pesticides sediment out of the water layer to the benthic sediment layer. The net sedimentation effect depends on settling velocity of the particles and the shear stress at the sediment-water interface. Near the sea-bed sedimentation and resuspension occur simultaneously and the net flux depends on which process dominates. In the modelling literature, it is commonly assumed that deposition into the sediment pool from the water only occurs when the shear stress (turbulence) at the sediment surface is less than a critical value. As pesticides are sorbed on multiple groups of particles, it is recommended that modelling should simulate different groups of particle-sorbing pesticides (see Adsorption/desorption section above), each of which will have a characteristic settling velocity, $V$.

Taking into account the main sedimentation types (settling of the flocculated and sorbed pesticides) in aquatic systems, the overall sedimentation rate ($k_{sed}$) can be described as follows (Hipsey et al., 2008):

\begin{eqnarray}
f_{set-P}^{pst} = \frac{V_s^p} {\Delta z} C_p
\end{eqnarray}

where:

* $f_{set-P}^{pst}$ is the sedimentation rate of pesticide sorbed to the P th particulate group 
* $V_s$ is the settling vertical velocity of the sorbed pesticides
* $Δz$ is the vertical dimension of the computational cell

In addition, dissolved organic contaminants (including pesticides) can come into the particulate phase due to flocculation with dissolved humic substances during mixing of fresh water and seawater (Poerschmann et al., 2008; Sholkovitz, 1976). Flocculation is important in estuaries and is strongly salinity-dependent. Sholkovitz (1976) reported that the amount of flocculated pesticides increased significantly as salinity raised from 0 to 15-20‰, and the flocculated dissolved organic and inorganic materials varied between 3 - 11% and 2 – 6 %, respectively. The flocculated pesticides can settle to the benthic sediment layer. This effect can be captured by resolving the flocculation effect, dynamically computing the floc velocity $V_s^{floc}$ and assigning sedimentation loss to the relevant pesticide pool in a similar fashion to the above equation.


#### Resuspension {-}

Sorbed pesticides in the sediment layer can be transported into the water layer when the shear stress at the sediment surface is greater than a critical shear stress of erosion. Resuspension is an important process in modelling the fate of pesticides in aquatic systems, especially in environments subject to strong currents and wave. Resuspension of pesticides is estimated from the resuspension rates of the particles and the concentration of pesticides in the benthic sediment, with pesticides assumed to be sorbed among different groups of particles based on the partitioning rates. The specific resuspension rate can be expressed for each sorbed group (Hipsey et al., 2008):

\begin{eqnarray}
\hat f_{res-p}^{pst} = \chi_{p-sed} \underbrace{\alpha_{res} (max(\frac{\tau - \tau_c} {\tau_{ref}}, 0))}_\text{sediment resuspension} \frac{1} {\Delta z_{bot}}
\end{eqnarray}

where:

* $\hat f_{res-p}^{pst}$ is the resuspension rate of pesticide on the $P^{th}$ th group in the bottom cell
* $\chi_{p-sed}$ is the fraction of pesticides partitioned onto the $P^{th}$ particle group (mg pesticide /mg particle)
* $\alpha_{res}$ is the resuspension rate constant for sediment
* $\tau$ is the shear stress
* $\tau_c$ is the critical erosion shear stress for each group of particles
* $\tau_{ref}$ is the reference shear stress
* $\Delta z_{bot}$ is the depth of the bottom water layer



#### Pesticides within the sediment pool {-}

Pesticides stored within the sediment layer are subject to several processes such as sedimentation (deposition of new material into the sediment compartment), resuspension into the water layer, and dissolved diffusive flux (exchange with water layer). Sedimentation and resuspension are impacted by turbulence (wind-induced mixing, storm surges, and internal waves and seiches) and shear flow in water body. Diffusive flux is based on the concentration gradient-dependent process. The equation for pesticide dynamics in the sediment layer is:

\begin{eqnarray}
\frac{dC_{sed}^{pst}}{dt} = \check{f}_{sed-set}^{pst} - \hat{f}_{sed-res}^{pst} \pm f_{sed-dif}^{pst}
\end{eqnarray}

Sedimentation $\check{f}_{sed-set}^{pst}$ and resuspension $\check{f}_{sed-set}^{pst}$ mechanisms of pesticides in the benthic layer can be explained similarly to those in the water compartment. Diffusive flux of pesticides $f_{sed-dif}^{pst}$ is defined in units of mass per area and time and defined by the form of Fick’s First law. Positive diffusive flux means deposition from the water layer onto the benthic layer and negative flux indicates release from the benthic layer. The specific diffusive rate across the sediment-water interface can be expressed in the following equation (Fernandez et al., 2014; Minick & Anderson, 2017):

\begin{eqnarray}
f_{sed-dif}^{pst} = -\frac {D_w}{\delta_L} (C_w - C_{pw})
\end{eqnarray}

where:

* $f_{sed-dif}^{pst}$ is the the specific diffusive rate across the sediment-water interface 
* $D_w$ is the pesticide (compound) specific diffusion coefficient in water
* $\delta_L$ is is the thickness of stagnant water layer between benthic sediment and water layers (also called boundary layer thickness)
* $C_w$ is the freely dissolved concentration in water 
* $C_pw$ is the freely dissolved concentration in porewater

In modelling practe, measuring accurate boundary layer thickness is difficult but it significantly affects the result of estimating the magnitude of diffusive flux. Users may therefore alternatively choose to prescribe a "static" release rate . 


### Variable Summary

The default variables created by this module are summarised in Table \@ref(tab:......). The diagnostic outputs able to be output are summarised in Table \@ref(tab:......).


### Parameter Summary

The parameters and settings used by this module are summarised in Table \@ref(tab:......).

### Optional Module Links

This module can be linked to the following other AED modules:

-   [aed_phytoplankton][Phytoplankton]: phytoplankton rate of productivity ($GPP$) is able to drive the biological uptake rate of pesticide.


### Feedbacks to the Host Model

The pesticide module has no feedbacks to the host hydrodynamic
model.


## Setup and Configuration

An example `aed.nml` parameter specification block for the `aed_pesticides`
module that is modelling one pesticide is shown below:

```{fortran, eval = FALSE}
&aed_pesticides
   num_pesticides     =  1
   the_pesticides     =  1
  !--[ module options ]--!
   simVolatilisation  = .false.
     pst_piston_model =  1
   simSorption        = .false.
   simPhotolysis      = .false.
   simUptake          = .false.
     gpp_variable     = 'PHY_gpp'
   simSediment        = .true.
     initSedimentConc = .false.
   simResuspension    = .false.
     resuspension     =  0
  !--[ advanced settings ]--!
   dbase              = './aed_pesticide_pars.csv'
   diag_level         = 10
/
```


<br>

The numbers and settings reported here are for example purposes and should be reviewed before use based on the users chosen site context. 

<br>


```{block2, pstnote-text, type='rmdnote'}
In addition to adding the above code block to `aed.nml`, users must also supply a valid AED pesticide parameter database file (`aed_pesticide_pars`). 
The database file must be supplied in `CSV` format. 

Users can create a standard file in the correct format from the online [**AED parameter database**](https://aed.see.uwa.edu.au/research/models/AED/aed_dbase/db_edit.php) by selecting from the available groups of interest, downloading via the **"Make CSV"** button, and then tailoring to the simulation being undertaken as required. Carefully check the parameter units and values!
```


## Case Studies and Examples

Simulations have been performed to evaluate the model prediction capacity for four pesticides (*atrazine*, *metolachlor*, *imidacloprid*, and *pendimethalin*) in the case study of [Johnstone River](https://en.wikipedia.org/wiki/Johnstone_River) in Queensland, to assess how estuaries attenuate the passage of pesticides before they are released to the Great Barrier Reef.

<br>

<center>

```{r johnstone-map, fig.cap="Map of Johnstone estuary, Australia.", echo=FALSE, message=FALSE, warning=FALSE, width = 501, height = 385}
library(leaflet)
leaflet(height=385, width=500) %>%
  setView(lng = 146.07, lat = -17.505, zoom = 11) %>%
  addTiles() %>%
  addProviderTiles(providers$Stamen.Terrain)  %>%
  addMarkers(lng = 146.06, lat = -17.51, popup = "Johnstone River Estuary")
```

</center>
